# Generated by Django 4.1 on 2023-08-24 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(choices=[(1, 'chapter one'), (2, 'chapter Two'), (3, 'chapter Three'), (4, 'chapter Four'), (5, 'chapter Five'), (6, 'chapter Six'), (7, 'chapter Seven'), (8, 'chapter Eight'), (9, 'chapter Nine'), (10, 'chapter Ten'), (11, 'chapter Eleven'), (12, 'chapter Twelve')])),
                ('type', models.CharField(choices=[('activity', 'Activity'), ('student', 'Student')], default='activity', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('choices', 'Choices'), ('tof', 'True Or False')], max_length=15)),
                ('marker', models.TimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='grade12.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='TFQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.BooleanField()),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade12.text')),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer_1', models.CharField(max_length=200)),
                ('answer_2', models.CharField(max_length=200)),
                ('answer_3', models.CharField(max_length=200)),
                ('answer_4', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade12.text')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade12.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Multiples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer_1', models.CharField(max_length=200)),
                ('answer_2', models.CharField(max_length=200)),
                ('answer_3', models.CharField(max_length=200)),
                ('answer_4', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('grammar', 'Grammar'), ('phonetics', 'Phonetics'), ('vocabulary', 'Vocabulary')], max_length=30)),
                ('correct_answer', models.CharField(max_length=200)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade12.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='MakeQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('underlined_word', models.CharField(max_length=30)),
                ('answer_1', models.CharField(max_length=200)),
                ('answer_2', models.CharField(blank=True, max_length=200, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade12.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectTheMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('error1', models.CharField(max_length=30)),
                ('error2', models.CharField(max_length=30)),
                ('error3', models.CharField(max_length=30)),
                ('error4', models.CharField(max_length=30)),
                ('correction1', models.CharField(max_length=30)),
                ('correction2', models.CharField(max_length=30)),
                ('correction3', models.CharField(max_length=30)),
                ('correction4', models.CharField(max_length=30)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade12.chapter')),
            ],
        ),
    ]
