# Generated by Django 4.1 on 2023-08-31 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(choices=[('1a', 'chapter one activity'), ('1s', 'chapter one student'), ('2a', 'chapter two activity'), ('2s', 'chapter two student'), ('3a', 'chapter three activity'), ('3s', 'chapter three student'), ('4a', 'chapter four activity'), ('4s', 'chapter four student'), ('5a', 'chapter five activity'), ('5s', 'chapter five student'), ('6a', 'chapter six activity'), ('6s', 'chapter six student'), ('7a', 'chapter seven activity'), ('7s', 'chapter seven student'), ('8a', 'chapter eight activity'), ('8s', 'chapter eight student'), ('9a', 'chapter nine activity'), ('9s', 'chapter nine student'), ('10a', 'chapter ten activity'), ('10s', 'chapter ten student'), ('11a', 'chapter eleven activity'), ('11s', 'chapter eleven student'), ('12a', 'chapter twelve activity'), ('12s', 'chapter twelve student')], max_length=3)),
            ],
            options={
                'verbose_name': '0- Chapter',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(choices=[(7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')])),
            ],
            options={
                'verbose_name': '-1 Grade',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('choices', 'Choices'), ('tof', 'True Or False')], max_length=15)),
                ('marker', models.TimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='grade9.chapter')),
            ],
            options={
                'verbose_name': '1- Text',
            },
        ),
        migrations.CreateModel(
            name='TFQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.BooleanField()),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade9.text')),
            ],
            options={
                'verbose_name': '3- True Or False Question',
            },
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer_1', models.CharField(max_length=200)),
                ('answer_2', models.CharField(max_length=200)),
                ('answer_3', models.CharField(max_length=200)),
                ('answer_4', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade9.text')),
            ],
            options={
                'verbose_name': '2- Choices for Text',
            },
        ),
        migrations.CreateModel(
            name='Paragraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade9.chapter')),
            ],
            options={
                'verbose_name': '7- Paragraph',
            },
        ),
        migrations.CreateModel(
            name='Multiples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer_1', models.CharField(max_length=200)),
                ('answer_2', models.CharField(max_length=200)),
                ('answer_3', models.CharField(max_length=200)),
                ('answer_4', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('grammar', 'Grammar'), ('phonetics', 'Phonetics'), ('vocabulary', 'Vocabulary')], max_length=30)),
                ('correct_answer', models.CharField(max_length=200)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade9.chapter')),
            ],
            options={
                'verbose_name': '4- Multiple Options Question',
            },
        ),
        migrations.CreateModel(
            name='MakeQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('underlined_word', models.CharField(max_length=30)),
                ('answer_1', models.CharField(max_length=200)),
                ('answer_2', models.CharField(blank=True, max_length=200, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade9.chapter')),
            ],
            options={
                'verbose_name': '5- Forming Question',
            },
        ),
        migrations.CreateModel(
            name='CTMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('error1', models.CharField(max_length=90)),
                ('error2', models.CharField(max_length=90)),
                ('error3', models.CharField(max_length=90)),
                ('error4', models.CharField(max_length=90)),
                ('correct_answer', models.CharField(max_length=90)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade9.chapter')),
            ],
            options={
                'verbose_name': '8- Choose the mistake',
            },
        ),
        migrations.CreateModel(
            name='CorrectTheMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('error1', models.CharField(max_length=30)),
                ('correction1', models.CharField(max_length=30)),
                ('error2', models.CharField(max_length=30)),
                ('correction2', models.CharField(max_length=30)),
                ('error3', models.CharField(max_length=30)),
                ('correction3', models.CharField(max_length=30)),
                ('error4', models.CharField(max_length=30)),
                ('correction4', models.CharField(max_length=30)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade9.chapter')),
            ],
            options={
                'verbose_name': '6- Find the mistake',
            },
        ),
    ]
