# Generated by Django 4.1 on 2023-08-31 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade9', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='grade',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='grade9.grade'),
            preserve_default=False,
        ),
    ]
