# Generated by Django 4.1 on 2023-08-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade9', '0003_remove_chapter_type_alter_chapter_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('error1', models.CharField(max_length=90)),
                ('error2', models.CharField(max_length=90)),
                ('error3', models.CharField(max_length=90)),
                ('error4', models.CharField(max_length=90)),
                ('correct_answer', models.CharField(max_length=90)),
            ],
            options={
                'verbose_name': '8- Choose the mistake',
            },
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': '0- Chapter'},
        ),
        migrations.AlterModelOptions(
            name='correctthemistake',
            options={'verbose_name': '6- Find the mistake'},
        ),
        migrations.AlterModelOptions(
            name='makequestions',
            options={'verbose_name': '5- Forming Question'},
        ),
        migrations.AlterModelOptions(
            name='multiples',
            options={'verbose_name': '4- Multiple Options Question'},
        ),
        migrations.AlterModelOptions(
            name='paragraphs',
            options={'verbose_name': '7- Paragraph'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': '1- Text'},
        ),
        migrations.AlterModelOptions(
            name='textquestion',
            options={'verbose_name': '2- Choices for Text'},
        ),
        migrations.AlterModelOptions(
            name='tfquestions',
            options={'verbose_name': '3- True Or False Question'},
        ),
    ]
