# Generated by Django 4.1 on 2023-08-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade9', '0004_ctmistake_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctmistake',
            name='correct_answer',
            field=models.CharField(choices=[('<django.db.models.fields.CharField>', 'option 1')], max_length=90),
        ),
    ]
