# Generated by Django 4.1 on 2023-08-27 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade9', '0005_alter_ctmistake_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctmistake',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grade9.chapter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ctmistake',
            name='correct_answer',
            field=models.CharField(max_length=90),
        ),
    ]
